services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    depends_on:
      - postgres
    command: sh -c "npm start"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: finance_bot
      DB_USER: postgres
      DB_PASSWORD: password123
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./auth_info:/app/auth_info